# .woodpecker.yml
pipeline:
  build:
    image: jekyll/jekyll
    secrets: [ codeberg_access_token ]
    commands:
      - chmod -R 777 .
      - bundle install
      - bundle exec jekyll build
      - git config --global --add safe.directory /woodpecker/src/codeberg.org/jwildeboer/fedigridsource/_site
      - cp domains _site/.domains
      - cd _site
      - git init
      - git add --all
      - git remote add up $CODEBERG_ACCESS_TOKEN@https://codeberg.org/jwildeboer/fedigrid.git
      - git push -u up pages -f