# .woodpecker.yml
pipeline:
  build:
    image: jekyll/jekyll
    secrets: [ cbtoken, cbmail ]
    commands:
      - chmod -R 777 .
      - mkdir _site
      - cd _site
      - git config --global --add safe.directory /woodpecker/src/codeberg.org/jwildeboer/fedigridsource/_site
      - git config --global user.email "$CBMAIL"
      - git config --global user.name "CI Builder"
      - git config --global init.defaultBranch pages
      - git clone https://$CBTOKEN@codeberg.org/jwildeboer/fedigrid.git
      - git remote set-url origin https://$CBTOKEN@codeberg.org/jwildeboer/fedigrid.git
      - git branch -m pages
      - chmod -R 777 .
      - cd ..
      - bundle install
      - bundle exec jekyll build
      - cp domains _site/.domains
      - cd _site
      - ls -lisa
      - git status
      - git add --all
      - git commit -m "Woodpecker CI Jekyll Build"
      - git push 