# .woodpecker.yml
pipeline:
  build:
    image: jekyll/jekyll
    secrets: [ cbtoken ]
    commands:
      - echo $$CBTOKEN
      - chmod -R 777 .
      - bundle install
      - bundle exec jekyll build
      - git config --global --add safe.directory /woodpecker/src/codeberg.org/jwildeboer/fedigridsource/_site
      - cp domains _site/.domains
      - cd _site
      - git init
      - git branch -m pages
      - git config user.email "jan@wildeboer.net"
      - git config user.name "CI Builder"
      - git remote add origin $$CBTOKEN@https://codeberg.org/jwildeboer/fedigrid.git
      - git add --all
      - git commit -m "CI Build"
      - git push origin pages -f